apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  cmSecret.xml: |
     This part is not encrypted. {{ .Values.cmSecret }}