apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-cm
  namespace: {{ .Values.namespace }}
data:
{{ printf "environments/configmap.%s.yaml" .Values.namespace | .Files.Get | indent 2 }}