kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name }}-route
  namespace: {{ .Values.namespace }}
spec:
  to:
    kind: Service
    name: {{ .Values.name }}-svc
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
