name: OpenShift Application Deployment

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 9 5 * *'
  push:
    branches: [ "main" ]
    tags: 
     - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: quay.io
  IMAGE_NAME: cpranava0/mocf-api
  DOCKER_FILE_LOCATION: ./Dockerfile
  DOCKER_SECRET: ${{ secrets.QUAY_TOKEN }} 
  DOCKER_USER: cpranava0+githubsa
  
jobs:
  build_push:
    name: Build and Push to Container Registry
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          containerfiles: ${{ env.DOCKER_FILE_LOCATION }}

      - name: Push to GitHub Container Repository
        id: push-to-docker-io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.meta.outputs.tags }}
          registry: ${{ env.REGISTRY }} 
          username: ${{ env.DOCKER_USER }} 
          password: ${{ env.DOCKER_SECRET }} 
